version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt  # If you have any dependencies
      
  pre_build:
    commands:
      - echo "Running pre-build steps..."
      - python --version
      - pip --version
      
  build:
    commands:
      - echo "Building the Python application..."
      - python hello.py
      - echo "Build completed successfully."
      
  post_build:
    commands:
      - echo "Running post-build steps..."
      - echo "Build finished on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: '.'
